import {
  Accessibility,
  Archive,
  Biohazard,
  Bomb,
  BookMarked,
  BookOpenText,
  Brain,
  BriefcaseBusiness,
  Building2,
  Church,
  CircleDollarSign,
  Clapperboard,
  CloudLightning,
  Compass,
  Construction,
  Cpu,
  Crown,
  Earth,
  Eye,
  Factory,
  Flag,
  FlaskConical,
  Flower2,
  Gavel,
  Globe,
  Globe2,
  GraduationCap,
  Hammer,
  HandHeart,
  HardHat,
  HeartCrack,
  HeartPulse,
  Hospital,
  Landmark,
  LandPlot,
  Leaf,
  Lightbulb,
  LockKeyhole,
  Map,
  MapPinned,
  Medal,
  Megaphone,
  MessageSquareQuote,
  Newspaper,
  NotebookPen,
  Palette,
  PawPrint,
  Pill,
  Plane,
  Radiation,
  Rainbow,
  Route,
  Scale,
  ScrollText,
  Search,
  ShieldAlert,
  ShieldX,
  Stethoscope,
  Swords,
  TrendingDown,
  Trophy,
  Unlink,
  UserRound,
  Users,
  UsersRound,
  Vote,
  Waves,
  Wheat,
  type LucideIcon,
} from "lucide-react";

const topicIcons: Record<string, LucideIcon> = {
  "american-politics": Landmark,
  "democracy-and-elections": Vote,
  "presidency-and-executive-power": Crown,
  "constitutional-history": ScrollText,
  "law-and-legal-change": Scale,
  "courts-and-trials": Gavel,
  "crime-policing-and-violence": ShieldAlert,
  "prisons-and-incarceration": LockKeyhole,
  "war-and-military-strategy": Swords,
  "soldiers-veterans-and-combat-experience": Medal,
  "american-civil-war": Flag,
  "world-war-i": Bomb,
  "world-war-ii": Plane,
  "vietnam-war": MapPinned,
  "cold-war-and-nuclear-politics": Radiation,
  "intelligence-secrecy-and-surveillance": Eye,
  holocaust: BookMarked,
  "genocide-atrocity-and-political-violence": ShieldX,
  "empire-and-colonialism": Globe2,
  "slavery-and-emancipation": Unlink,
  reconstruction: Hammer,
  "indigenous-history": LandPlot,
  "civil-rights-and-racial-justice": HandHeart,
  "black-history-and-culture": Users,
  "immigration-refugees-and-borderlands": Route,
  "latin-america-and-the-caribbean": Earth,
  "europe-and-russia": Globe2,
  "asia-and-the-pacific": Globe,
  "middle-east-and-north-africa": Globe2,
  "africa-and-the-african-diaspora": Earth,
  "religion-and-religious-movements": Church,
  "evangelicalism-and-christian-nationalism": Church,
  "gender-and-feminism": UsersRound,
  "lgbtq-history-and-life": Rainbow,
  "reproductive-rights-and-family-policy": HeartPulse,
  "family-childhood-and-adoption": UsersRound,
  "political-biography": Landmark,
  "presidential-biography": Crown,
  "military-biography": Medal,
  "literary-biography": BookOpenText,
  "artistic-biography": Palette,
  "scientific-biography": FlaskConical,
  "business-biography": BriefcaseBusiness,
  "religious-biography": Church,
  "sports-biography": Trophy,
  "activist-biography": Megaphone,
  "family-biography": UsersRound,
  "group-biography": Users,
  "intellectual-biography": Lightbulb,
  "biography-and-public-lives": UserRound,
  "memoir-and-personal-history": NotebookPen,
  "grief-trauma-and-recovery": HeartCrack,
  "intellectual-history-and-ideas": Lightbulb,
  "literature-and-writers": BookOpenText,
  "art-music-and-performance": Palette,
  "film-television-and-popular-culture": Clapperboard,
  "media-journalism-and-public-opinion": Newspaper,
  "social-movements-and-activism": Megaphone,
  "class-poverty-and-inequality": TrendingDown,
  "housing-cities-and-urban-life": Building2,
  "labor-work-and-organizing": HardHat,
  "business-capitalism-and-corporations": BriefcaseBusiness,
  "money-markets-and-economic-policy": CircleDollarSign,
  "food-agriculture-and-land": Wheat,
  "infrastructure-engineering-and-built-environment": Construction,
  "technology-computing-and-ai": Cpu,
  "science-and-discovery": FlaskConical,
  "medicine-health-and-the-body": Stethoscope,
  "disease-epidemics-and-drugs": Biohazard,
  "mental-health-and-psychology": Brain,
  "disability-and-difference": Accessibility,
  "climate-weather-and-disaster": CloudLightning,
  "environment-conservation-and-pollution": Leaf,
  "natural-history-and-animals": PawPrint,
  "oceans-rivers-and-water": Waves,
  "energy-extraction-and-resources": Factory,
  "travel-exploration-and-place": Compass,
  "regional-and-local-history": MapPinned,
  "education-and-universities": GraduationCap,
  "sports-and-athletes": Trophy,
  "death-memory-and-commemoration": Flower2,
  "archives-museums-and-historical-method": Archive,
  "settler-colonialism": Map,
  "migration-and-diaspora": Route,
  "nationalism-and-authoritarianism": Flag,
  "human-rights-and-international-law": Scale,
  "public-health-systems": Hospital,
  "drugs-addiction-and-treatment": Pill,
  "essays-and-cultural-criticism": MessageSquareQuote,
};

export function TopicIcon({ slug, size = 18 }: { slug: string; size?: number }) {
  const Icon = topicIcons[slug] ?? Search;
  return <Icon aria-hidden="true" size={size} strokeWidth={1.65} />;
}

export const topicIconCount = Object.keys(topicIcons).length;
