import fs from "node:fs/promises";
import path from "node:path";
import { data, getBookStats } from "../lib/data";
import type { Book } from "../lib/types";
import { publicDataDir, root, sourcesDir } from "./build/paths";

type CoverPatch = {
  generatedAt: string;
  notes: string;
  books: Record<string, Partial<Book>>;
  failures?: Record<string, CoverFailure>;
};

type CoverFailure = {
  sourceUrl?: string;
  failedAt: string;
  note?: string;
};

type CoverCacheReport = {
  generatedAt: string;
  summary: Record<CoverCacheStatus, number> & {
    selected: number;
    cachedBooks: number;
  };
  rows: CoverCacheRow[];
};

type CoverCacheStatus = "cached" | "already_local" | "existing_file" | "skipped" | "failed";

type CoverCacheRow = {
  bookId: string;
  title: string;
  status: CoverCacheStatus;
  sourceUrl?: string;
  localUrl?: string;
  note?: string;
};

type CliOptions = {
  limit: number;
  concurrency: number;
  retryFailures: boolean;
  provider?: "openlibrary" | "google" | "all";
};

const outputDir = path.join(root, "public", "book-covers");
const patchPath = path.join(sourcesDir, "enrichment", "covers.generated.json");
const reportPath = path.join(publicDataDir, "cover-cache-report.json");
const defaultLimit = 100;
const defaultConcurrency = 4;
const timeoutMs = 12_000;
const minImageBytes = 800;

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const existingPatch = await readPatch();
  const selected = data.books
    .filter((book) => shouldSelectBook(book, existingPatch, options))
    .sort(compareBooksForCoverCaching)
    .slice(0, options.limit);

  await fs.mkdir(outputDir, { recursive: true });

  const rows = await runPool(selected, options.concurrency, (book) => cacheCoverForBook(book, existingPatch));
  const nextPatch = mergePatch(existingPatch, rows);
  await fs.writeFile(patchPath, `${JSON.stringify(nextPatch, null, 2)}\n`);

  const summary = summarize(rows, selected.length, Object.keys(nextPatch.books).length);
  await fs.writeFile(
    reportPath,
    `${JSON.stringify(
      {
        generatedAt: nextPatch.generatedAt,
        summary,
        rows,
      } satisfies CoverCacheReport,
      null,
      2,
    )}\n`,
  );

  console.log(
    `Cached ${summary.cached} covers. Reused ${summary.existing_file} existing files. ` +
      `Patch now contains ${summary.cachedBooks} local cover URLs. Report written to data/public/cover-cache-report.json.`,
  );
}

function parseArgs(args: string[]): CliOptions {
  const options: CliOptions = {
    limit: defaultLimit,
    concurrency: defaultConcurrency,
    retryFailures: false,
    provider: "all",
  };

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    const next = args[index + 1];
    if (arg === "--limit" && next) {
      options.limit = parsePositiveInteger(next, "limit");
      index += 1;
    } else if (arg === "--concurrency" && next) {
      options.concurrency = parsePositiveInteger(next, "concurrency");
      index += 1;
    } else if (arg === "--retry-failures") {
      options.retryFailures = true;
    } else if (arg === "--provider" && next) {
      if (next !== "openlibrary" && next !== "google" && next !== "all") {
        throw new Error(`Unsupported provider: ${next}`);
      }
      options.provider = next;
      index += 1;
    }
  }

  return options;
}

function parsePositiveInteger(value: string, label: string) {
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed) || parsed < 1) throw new Error(`--${label} must be a positive integer.`);
  return parsed;
}

async function readPatch(): Promise<CoverPatch> {
  const failures = await readPreviousFailures();
  try {
    const patch = JSON.parse(await fs.readFile(patchPath, "utf8")) as CoverPatch;
    return {
      ...patch,
      failures: sortRecord({ ...failures, ...(patch.failures ?? {}) }),
    };
  } catch {
    return {
      generatedAt: new Date().toISOString(),
      notes: "Generated by scripts/cache-book-covers.ts. Downloads remote catalog cover thumbnails into public/book-covers and rewrites thumbnailUrl to local static assets.",
      books: {},
      failures,
    };
  }
}

async function readPreviousFailures() {
  try {
    const report = JSON.parse(await fs.readFile(reportPath, "utf8")) as CoverCacheReport;
    const failures: Record<string, CoverFailure> = {};
    for (const result of report.rows) {
      if (result.status !== "failed") continue;
      failures[result.bookId] = {
        sourceUrl: result.sourceUrl,
        failedAt: report.generatedAt,
        note: result.note,
      };
    }
    return sortRecord(failures);
  } catch {
    return {};
  }
}

function shouldSelectBook(book: Book, patch: CoverPatch, options: CliOptions) {
  const thumbnailUrl = book.thumbnailUrl;
  if (!thumbnailUrl) return false;
  if (isLocalCoverUrl(thumbnailUrl)) return false;
  if (!options.retryFailures && patch.books[book.id]?.thumbnailUrl && isLocalCoverUrl(patch.books[book.id]?.thumbnailUrl)) return false;
  if (!options.retryFailures && patch.failures?.[book.id]?.sourceUrl === thumbnailUrl) return false;
  if (options.provider === "openlibrary" && !isOpenLibraryCover(thumbnailUrl)) return false;
  if (options.provider === "google" && !isGoogleBooksCover(thumbnailUrl)) return false;
  return isOpenLibraryCover(thumbnailUrl) || isGoogleBooksCover(thumbnailUrl);
}

function compareBooksForCoverCaching(a: Book, b: Book) {
  const scoreDelta = coverPriorityScore(b) - coverPriorityScore(a);
  if (scoreDelta !== 0) return scoreDelta;
  return a.title.localeCompare(b.title);
}

function coverPriorityScore(book: Book) {
  const stats = getBookStats(book.id);
  const recognition = (stats.wins ?? 0) * 12 + (stats.lists ?? 0) * 3;
  const sourceScore = isOpenLibraryCover(book.thumbnailUrl) ? 2 : 1;
  return recognition + sourceScore;
}

async function cacheCoverForBook(book: Book, patch: CoverPatch): Promise<CoverCacheRow> {
  const sourceUrl = book.thumbnailUrl;
  if (!sourceUrl) return row(book, "skipped", { note: "Book has no thumbnail URL." });
  if (isLocalCoverUrl(sourceUrl)) return row(book, "already_local", { localUrl: sourceUrl });

  const downloadUrl = normalizedDownloadUrl(sourceUrl);
  const extension = extensionForUrl(downloadUrl);
  const fileName = `${book.id}.${extension}`;
  const filePath = path.join(outputDir, fileName);
  const localUrl = `/book-covers/${fileName}`;

  if (patch.books[book.id]?.thumbnailUrl === localUrl) {
    return row(book, "already_local", { sourceUrl, localUrl });
  }

  try {
    const existing = await fs.stat(filePath);
    if (existing.size >= minImageBytes) return row(book, "existing_file", { sourceUrl, localUrl });
  } catch {
    // File is not cached yet.
  }

  try {
    const bytes = await downloadImage(downloadUrl);
    await fs.writeFile(filePath, bytes);
    return row(book, "cached", { sourceUrl, localUrl });
  } catch (error) {
    return row(book, "failed", {
      sourceUrl,
      note: error instanceof Error ? error.message : String(error),
    });
  }
}

async function downloadImage(url: string) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(url, {
      redirect: "follow",
      signal: controller.signal,
      headers: {
        "user-agent": "Book Prize Index cover cache (https://book-prize-index.local)",
        accept: "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
      },
    });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const contentType = response.headers.get("content-type") ?? "";
    if (!contentType.startsWith("image/")) throw new Error(`Unexpected content-type: ${contentType || "unknown"}`);
    const buffer = Buffer.from(await response.arrayBuffer());
    if (buffer.length < minImageBytes) throw new Error(`Image response too small: ${buffer.length} bytes`);
    return buffer;
  } finally {
    clearTimeout(timeout);
  }
}

function mergePatch(existingPatch: CoverPatch, rows: CoverCacheRow[]): CoverPatch {
  const books = { ...existingPatch.books };
  const failures = { ...(existingPatch.failures ?? {}) };
  for (const result of rows) {
    if ((result.status === "cached" || result.status === "existing_file") && result.localUrl) {
      books[result.bookId] = {
        ...(books[result.bookId] ?? {}),
        thumbnailUrl: result.localUrl,
      };
      delete failures[result.bookId];
    } else if (result.status === "failed") {
      failures[result.bookId] = {
        sourceUrl: result.sourceUrl,
        failedAt: new Date().toISOString(),
        note: result.note,
      };
    }
  }

  return {
    generatedAt: new Date().toISOString(),
    notes: existingPatch.notes,
    books: sortRecord(books),
    failures: sortRecord(failures),
  };
}

async function runPool<T, R>(items: T[], concurrency: number, worker: (item: T) => Promise<R>) {
  const results = new Array<R>(items.length);
  let nextIndex = 0;
  const workers = Array.from({ length: Math.min(concurrency, items.length) }, async () => {
    while (nextIndex < items.length) {
      const currentIndex = nextIndex;
      nextIndex += 1;
      results[currentIndex] = await worker(items[currentIndex]);
    }
  });
  await Promise.all(workers);
  return results;
}

function summarize(rows: CoverCacheRow[], selected: number, cachedBooks: number): CoverCacheReport["summary"] {
  const summary = {
    cached: 0,
    already_local: 0,
    existing_file: 0,
    skipped: 0,
    failed: 0,
    selected,
    cachedBooks,
  };
  for (const result of rows) summary[result.status] += 1;
  return summary;
}

function row(book: Book, status: CoverCacheStatus, detail: Omit<CoverCacheRow, "bookId" | "title" | "status"> = {}): CoverCacheRow {
  return {
    bookId: book.id,
    title: book.title,
    status,
    ...detail,
  };
}

function normalizedDownloadUrl(url: string) {
  if (isOpenLibraryCover(url)) return url.replace(/-([SML])\.jpg(\?.*)?$/i, "-M.jpg");
  return url.replace(/^http:\/\//, "https://");
}

function extensionForUrl(url: string) {
  const pathname = new URL(url).pathname.toLowerCase();
  if (pathname.endsWith(".png")) return "png";
  if (pathname.endsWith(".webp")) return "webp";
  return "jpg";
}

function isLocalCoverUrl(url: string | undefined): url is string {
  return Boolean(url?.startsWith("/book-covers/"));
}

function isOpenLibraryCover(url: string | undefined) {
  return Boolean(url?.includes("covers.openlibrary.org"));
}

function isGoogleBooksCover(url: string | undefined) {
  return Boolean(url?.includes("books.google.com/books/content"));
}

function sortRecord<T>(record: Record<string, T>) {
  return Object.fromEntries(Object.entries(record).sort(([a], [b]) => a.localeCompare(b))) as Record<string, T>;
}
