import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { data, getBookStats, imprintsById, publishersById } from "../lib/data";
import type { Book, BookReaderProfile, BookReaderTrait, SourceRef } from "../lib/types";

type TraitDefinition = {
  id: string;
  label: string;
  description: string;
};

type GeneratedReaderTraits = {
  generatedAt: string;
  notes: string;
  books: Record<string, Partial<Book>>;
  sources: Record<string, SourceRef>;
};

type ReportRow = {
  bookId: string;
  title: string;
  author: string;
  readerLevel: BookReaderProfile["readerLevel"];
  narrativeScore: number;
  accessibilityScore: number;
  scholarlyScore: number;
  traits: Array<{ id: string; score: number; confidence: string; evidence: string[] }>;
  warnings: string[];
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const taxonomyPath = path.join(root, "sources", "reader-traits.json");
const outputPath = path.join(root, "sources", "enrichment", "reader-traits.generated.json");
const reportPath = path.join(root, "data", "reports", "reader-traits-report.json");
const limit = positiveNumber(readArg("--limit"), data.books.length);

async function main() {
  const generatedAt = new Date().toISOString();
  const definitions = JSON.parse(await fs.readFile(taxonomyPath, "utf8")) as TraitDefinition[];
  const allowed = new Set(definitions.map((definition) => definition.id));
  const books = [...data.books]
    .sort((a, b) => (getBookStats(b.id).score - getBookStats(a.id).score) || a.title.localeCompare(b.title))
    .slice(0, limit);

  const output: GeneratedReaderTraits = {
    generatedAt,
    notes: "Generated by scripts/classify-reader-traits.ts using deterministic catalog-text heuristics. Reader traits are search/retrieval signals, not factual subject assignments; manual curation may override.",
    books: {},
    sources: {},
  };
  const report: ReportRow[] = [];

  for (const book of books) {
    const profile = classifyBook(book, allowed);
    output.books[book.id] = { readerProfile: profile };
    report.push({
      bookId: book.id,
      title: book.title,
      author: book.authors.map((author) => author.name).join(", "),
      readerLevel: profile.readerLevel,
      narrativeScore: profile.narrativeScore,
      accessibilityScore: profile.accessibilityScore,
      scholarlyScore: profile.scholarlyScore,
      traits: profile.traits,
      warnings: warningsForProfile(book, profile),
    });
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.mkdir(path.dirname(reportPath), { recursive: true });
  await fs.writeFile(outputPath, `${JSON.stringify(sortOutput(output), null, 2)}\n`);
  await fs.writeFile(
    reportPath,
    `${JSON.stringify({
      generatedAt,
      totalBooks: data.books.length,
      classifiedBooks: books.length,
      traitCounts: traitCounts(report),
      readerLevelCounts: countBy(report, (row) => row.readerLevel),
      review: report
        .filter((row) => row.warnings.length)
        .sort((a, b) => b.warnings.length - a.warnings.length || b.scholarlyScore - a.scholarlyScore || a.title.localeCompare(b.title))
        .slice(0, 500),
      report,
    }, null, 2)}\n`,
  );
  console.log(`Reader traits classified for ${books.length} books.`);
}

function classifyBook(book: Book, allowed: Set<string>): BookReaderProfile {
  const context = bookContext(book);
  const scores = new Map<string, { score: number; evidence: string[] }>();
  const add = (id: string, score: number, evidence: string) => {
    if (!allowed.has(id) || score <= 0) return;
    const current = scores.get(id) ?? { score: 0, evidence: [] };
    current.score += score;
    if (!current.evidence.includes(evidence)) current.evidence.push(evidence);
    scores.set(id, current);
  };

  addPatternScores(context, add);
  addTopicScores(book, add);
  addPublisherScores(book, context, add);
  addAwardScores(book, context, add);
  applyContextAdjustments(context, scores);

  const trait = (id: string) => Math.min(1, scores.get(id)?.score ?? 0);
  const scholarlyScore = clamp01(trait("scholarly") * 0.62 + trait("academic") * 0.48 + trait("dense") * 0.35 + trait("reference") * 0.18);
  const narrativeScore = clamp01(trait("narrative") * 0.46 + trait("character_driven") * 0.22 + trait("biographical") * 0.13 + trait("reported") * 0.12 - scholarlyScore * 0.24);
  const accessibilityScore = clamp01(trait("accessible") * 0.48 + trait("popular") * 0.32 + trait("narrative") * 0.12 + trait("reported") * 0.08 - trait("dense") * 0.42 - trait("academic") * 0.3 - trait("scholarly") * 0.18);
  const readerLevel = inferReaderLevel({ accessibilityScore, scholarlyScore, referenceScore: trait("reference"), popularScore: trait("popular") });

  const traits = [...scores.entries()]
    .map(([id, value]): BookReaderTrait => ({
      id,
      score: Number(Math.min(1, value.score).toFixed(3)),
      confidence: value.score >= 0.72 ? "high" : value.score >= 0.42 ? "medium" : "low",
      evidence: value.evidence.slice(0, 6),
    }))
    .filter((item) => item.score >= 0.18)
    .sort((a, b) => b.score - a.score || a.id.localeCompare(b.id));

  return {
    readerLevel,
    narrativeScore: Number(narrativeScore.toFixed(3)),
    accessibilityScore: Number(accessibilityScore.toFixed(3)),
    scholarlyScore: Number(scholarlyScore.toFixed(3)),
    traits,
    method: "deterministic_catalog_heuristics_v1",
  };
}

function addPatternScores(context: ReturnType<typeof bookContext>, add: (id: string, score: number, evidence: string) => void) {
  const { text, title } = context;
  const metaScholarly = hasMetaScholarlyContext(context);
  const genreStudy = hasGenreStudyContext(context);
  matchAny(text, [
    ["story of", 0.16],
    ["stories of", 0.16],
    ["true story", 0.34],
    ["tells the story", 0.32],
    ["story of how", 0.28],
    ["chronicles the", 0.22],
    ["chronicle of", 0.16],
    ["journey", 0.24],
    ["quest", 0.2],
    ["adventure", 0.22],
    ["murder", 0.18],
    ["scandal", 0.15],
    ["war correspondent", 0.18],
    ["resistance", 0.12],
    ["narrative history", 0.32],
    ["vividly told", 0.3],
    ["illuminates", 0.14],
    ["reads like", 0.24],
    ["unfolds", 0.14],
  ], (score, term) => add("narrative", metaScholarly ? score * 0.45 : score, `catalog text contains "${term}"`));
  matchAny(text, [
    ["life of", 0.22],
    ["biography of", 0.28],
    ["work of biography", 0.28],
    ["biographer", 0.18],
    ["portrait of", 0.18],
    ["family", 0.18],
    ["lives of", 0.22],
    ["members included", 0.18],
    ["people who", 0.14],
    ["father", 0.12],
    ["mother", 0.12],
    ["woman at the heart", 0.28],
  ], (score, term) => {
    const adjusted = genreStudy ? score * 0.35 : score;
    add("character_driven", adjusted, `catalog text contains "${term}"`);
    add("biographical", adjusted * 0.8, `catalog text contains "${term}"`);
  });
  matchAny(text, [
    ["memoir", 0.42],
    ["memoir of", 0.42],
    ["autobiography of", 0.34],
    ["my ", 0.08],
    ["personal history", 0.28],
    ["confessions", 0.22],
  ], (score, term) => add("memoiristic", genreStudy ? score * 0.3 : score, `catalog text contains "${term.trim()}"`));
  matchAny(text, [
    ["reporter", 0.24],
    ["reported", 0.22],
    ["investigation", 0.2],
    ["interviews", 0.18],
    ["fieldwork", 0.2],
    ["eyewitness", 0.18],
    ["dispatches", 0.2],
  ], (score, term) => add("reported", score, `catalog text contains "${term}"`));
  matchAny(text, [
    ["essay", 0.28],
    ["essays", 0.34],
    ["criticism", 0.2],
    ["reflections", 0.2],
    ["meditations", 0.2],
  ], (score, term) => add("essayistic", score, `catalog text contains "${term}"`));
  matchAny(text, [
    ["argues", 0.2],
    ["argument", 0.18],
    ["demonstrates", 0.2],
    ["critique", 0.18],
    ["theory", 0.18],
    ["thesis", 0.22],
    ["interpretation", 0.14],
    ["epistemologies", 0.34],
    ["historiography", 0.34],
    ["historiographical", 0.34],
    ["method", 0.16],
  ], (score, term) => add("argument_driven", score, `catalog text contains "${term}"`));
  matchAny(text, [
    ["sweeping", 0.26],
    ["from ", 0.04],
    ["global history", 0.26],
    ["history of", 0.16],
    ["big history", 0.3],
    ["overview", 0.22],
    ["survey", 0.18],
  ], (score, term) => add("synthesis", metaScholarly ? score * 0.55 : score, `catalog text contains "${term.trim()}"`));
  matchAny(text, [
    ["epistemolog", 0.36],
    ["historiograph", 0.36],
    ["monograph", 0.34],
    ["methodolog", 0.28],
    ["theoretical", 0.28],
    ["disciplinary", 0.2],
    ["historians", 0.2],
    ["scholarly", 0.26],
    ["academic", 0.24],
    ["colonial intellectuals", 0.22],
    ["identity formation", 0.2],
    ["source-base", 0.16],
    ["institutions", 0.1],
  ], (score, term) => {
    add("scholarly", score, `catalog text contains "${term}"`);
    add("academic", score * 0.75, `catalog text contains "${term}"`);
  });
  matchAny(text, [
    ["handbook", 0.46],
    ["guidebook", 0.34],
    ["encyclopedia", 0.5],
    ["catalogue", 0.34],
    ["catalog ", 0.3],
    ["atlas", 0.44],
    ["bibliography", 0.5],
    ["index to", 0.5],
    ["manual", 0.28],
  ], (score, term) => add("reference", score, `catalog text contains "${term.trim()}"`));
  matchAny(text, [
    ["lucid", 0.2],
    ["engaging", 0.24],
    ["vivid", 0.18],
    ["gripping", 0.26],
    ["readable", 0.3],
    ["general reader", 0.3],
    ["popular", 0.18],
    ["bestseller", 0.22],
    ["new york times bestseller", 0.32],
  ], (score, term) => {
    if (metaScholarly && !/\b(lucid|engaging|readable|general reader|bestseller)\b/.test(term)) return;
    add("accessible", score, `catalog text contains "${term}"`);
    add("popular", score * 0.8, `catalog text contains "${term}"`);
  });
  matchAny(text, [
    ["experimental", 0.34],
    ["fragment", 0.2],
    ["hybrid", 0.2],
    ["graphic memoir", 0.28],
    ["poetic", 0.2],
  ], (score, term) => add("experimental", score, `catalog text contains "${term}"`));
  matchAny(text, [
    ["volume i", 0.16],
    ["volume ii", 0.16],
    ["vol.", 0.14],
    ["companion", 0.2],
    ["epistemologies", 0.34],
    "histories epistemologies identities".includes(title) ? ["histories epistemologies identities", 0.42] : ["", 0],
  ], (score, term) => {
    if (!term) return;
    add("dense", score, `catalog text contains "${term}"`);
    add("scholarly", score * 0.7, `catalog text contains "${term}"`);
  });
  if (metaScholarly) {
    add("scholarly", 0.24, "meta-scholarly history-writing context");
    add("academic", 0.18, "meta-scholarly history-writing context");
    add("dense", 0.14, "meta-scholarly history-writing context");
  }
}

function addTopicScores(book: Book, add: (id: string, score: number, evidence: string) => void) {
  const topics = normalize(`${book.primarySubject ?? ""} ${book.subjects.join(" ")} ${book.primaryTopic ?? ""} ${book.topics.join(" ")}`);
  if (topics.includes("memoir")) add("memoiristic", 0.36, "memoir/autobiography subject or topic");
  if (topics.includes("biography")) add("biographical", 0.34, "biography subject or topic");
  if (topics.includes("journalism") || topics.includes("reportage")) add("reported", 0.34, "journalism/reportage subject or topic");
  if (topics.includes("literature") || topics.includes("criticism")) add("essayistic", 0.2, "literature/criticism subject or topic");
  if (topics.includes("intellectual history")) add("argument_driven", 0.18, "intellectual history topic");
  if (topics.includes("history") && (topics.includes("criticism") || topics.includes("theory") || topics.includes("literature"))) {
    add("scholarly", 0.14, "scholarly subject/topic combination");
    add("argument_driven", 0.12, "scholarly subject/topic combination");
  }
  if (topics.includes("artistic biography")) {
    add("biographical", 0.24, "artistic biography topic");
    add("character_driven", 0.18, "artistic biography topic");
  }
}

function addPublisherScores(book: Book, context: ReturnType<typeof bookContext>, add: (id: string, score: number, evidence: string) => void) {
  const publisher = context.publisher;
  const imprint = context.imprint;
  const pressText = normalize(`${publisher} ${imprint}`);
  if (/\buniversity press\b|\bharvard\b|\byale\b|\boxford\b|\bcambridge\b|\bprinceton\b|\bstanford\b|\bduke\b|\bcolumbia\b|\bcornell\b|\bcalifornia\b/.test(pressText)) {
    add("academic", 0.38, `academic press signal: ${[imprint, publisher].filter(Boolean).join(" / ")}`);
    add("scholarly", 0.28, `academic press signal: ${[imprint, publisher].filter(Boolean).join(" / ")}`);
  }
  if (/\brandom house\b|\bpenguin\b|\bharper\b|\bsimon\b|\bknopf\b|\bfarrar\b|\bnorton\b|\bpicador\b|\bdoubleday\b|\bliveright\b|\briverhead\b/.test(pressText)) {
    add("popular", 0.22, `trade publisher signal: ${[imprint, publisher].filter(Boolean).join(" / ")}`);
    add("accessible", 0.14, `trade publisher signal: ${[imprint, publisher].filter(Boolean).join(" / ")}`);
  }
}

function addAwardScores(book: Book, context: ReturnType<typeof bookContext>, add: (id: string, score: number, evidence: string) => void) {
  const awards = context.awards;
  if (/\bbiography\b/.test(awards)) add("biographical", 0.24, "biography award category");
  if (/\bcriticism\b/.test(awards)) add("essayistic", 0.18, "criticism award category");
  if (/\bhistory\b/.test(awards) && /\bamerican historical association|bancroft|cundill|wolfson\b/.test(awards)) {
    add("scholarly", 0.12, "history award recognition");
  }
  const stats = getBookStats(book.id);
  if (stats.majorWins || stats.majorShortlists) add("popular", 0.12, "major-award recognition");
}

function bookContext(book: Book) {
  const publisher = book.publisherId ? publishersById.get(book.publisherId)?.name ?? "" : "";
  const imprint = book.imprintId ? imprintsById.get(book.imprintId)?.name ?? "" : "";
  const awards = data.appearances
    .filter((appearance) => appearance.bookId === book.id)
    .map((appearance) => data.awards.find((award) => award.id === appearance.awardId))
    .filter(Boolean)
    .map((award) => [award?.name, award?.categoryName, award?.subjectAreas.join(" ")].filter(Boolean).join(" "))
    .join(" ");
  const text = normalize([
    book.title,
    book.subtitle,
    book.summary,
    book.displaySummary,
    book.primarySubject,
    book.subjects.join(" "),
    book.primaryTopic,
    book.topics.join(" "),
    book.subjectCategories?.map((category) => category.label).join(" "),
    publisher,
    imprint,
    awards,
  ].filter(Boolean).join(" "));
  return {
    awards: normalize(awards),
    imprint,
    publisher,
    text,
    title: normalize(book.title),
  };
}

function inferReaderLevel({
  accessibilityScore,
  scholarlyScore,
  referenceScore,
  popularScore,
}: {
  accessibilityScore: number;
  scholarlyScore: number;
  referenceScore: number;
  popularScore: number;
}): BookReaderProfile["readerLevel"] {
  if (referenceScore >= 0.42) return "reference";
  if (scholarlyScore >= 0.42 && accessibilityScore < 0.45) return "academic";
  if (accessibilityScore >= 0.5 || popularScore >= 0.48) return "popular";
  return "crossover";
}

function warningsForProfile(book: Book, profile: BookReaderProfile) {
  const warnings: string[] = [];
  if (!book.summary && profile.traits.length < 3) warnings.push("low text coverage");
  if (profile.accessibilityScore >= 0.55 && profile.scholarlyScore >= 0.55) warnings.push("accessible and scholarly both high");
  if (profile.narrativeScore >= 0.65 && profile.readerLevel === "academic") warnings.push("narrative but academic");
  return warnings;
}

function matchAny(text: string, rules: Array<[string, number]>, onMatch: (score: number, term: string) => void) {
  for (const [term, score] of rules) {
    if (term && text.includes(term)) onMatch(score, term);
  }
}

function applyContextAdjustments(context: ReturnType<typeof bookContext>, scores: Map<string, { score: number; evidence: string[] }>) {
  if (hasGenreStudyContext(context)) {
    scaleScore(scores, "character_driven", 0.45, "reduced because text appears to study narrative/biographical genres");
    scaleScore(scores, "biographical", 0.55, "reduced because text appears to study narrative/biographical genres");
    scaleScore(scores, "memoiristic", 0.45, "reduced because text appears to study narrative/biographical genres");
  }
  if (hasMetaScholarlyContext(context)) {
    scaleScore(scores, "narrative", 0.62, "reduced because text appears to be scholarly/meta-historical");
    scaleScore(scores, "accessible", 0.75, "reduced because text appears to be scholarly/meta-historical");
    scaleScore(scores, "popular", 0.82, "reduced because text appears to be scholarly/meta-historical");
  }
}

function scaleScore(scores: Map<string, { score: number; evidence: string[] }>, id: string, factor: number, evidence: string) {
  const current = scores.get(id);
  if (!current) return;
  current.score *= factor;
  if (!current.evidence.includes(evidence)) current.evidence.push(evidence);
}

function hasMetaScholarlyContext(context: ReturnType<typeof bookContext>) {
  const text = context.text;
  return /\b(historiograph|epistemolog|methodolog|theoretical|monograph|disciplinary|scholarly|academic|historians map|how to write|history-writing|historian s craft|source-base|identity formation|colonial intellectuals)\b/.test(text);
}

function hasGenreStudyContext(context: ReturnType<typeof bookContext>) {
  const text = context.text;
  return /\b(history of histories|history of autobiography|history of biography|genre of|genres of|literary form|autobiography and|biography and|epics chronicles romances inquiries|histories epistemologies identities)\b/.test(text);
}

function traitCounts(report: ReportRow[]) {
  const counts: Record<string, number> = {};
  for (const row of report) {
    for (const trait of row.traits) counts[trait.id] = (counts[trait.id] ?? 0) + 1;
  }
  return Object.fromEntries(Object.entries(counts).sort(([a], [b]) => a.localeCompare(b)));
}

function countBy<T>(items: T[], key: (item: T) => string) {
  const counts: Record<string, number> = {};
  for (const item of items) counts[key(item)] = (counts[key(item)] ?? 0) + 1;
  return counts;
}

function sortOutput(output: GeneratedReaderTraits) {
  return {
    ...output,
    books: Object.fromEntries(Object.entries(output.books).sort(([a], [b]) => a.localeCompare(b))),
    sources: Object.fromEntries(Object.entries(output.sources).sort(([a], [b]) => a.localeCompare(b))),
  };
}

function normalize(input: string) {
  return input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9&. -]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function clamp01(value: number) {
  return Math.max(0, Math.min(1, value));
}

function readArg(name: string) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function positiveNumber(value: string | undefined, fallback: number) {
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? Math.floor(parsed) : fallback;
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
