import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { data } from "../lib/data";
import type { Book, Imprint, Publisher, SourceRef } from "../lib/types";

type MappingConfidence = "high" | "medium" | "low";

type NormalizationMapping = {
  raw: string;
  imprint: string;
  publisher: string;
  confidence: MappingConfidence;
  note?: string;
};

type MappingFile = {
  generatedAt: string | null;
  notes: string;
  mappings: NormalizationMapping[];
};

type NormalizedPatch = {
  generatedAt: string;
  notes: string;
  books: Record<string, Partial<Book>>;
  imprints: Record<string, Partial<Imprint>>;
  publishers: Record<string, Partial<Publisher>>;
  sources: Record<string, SourceRef>;
};

type ReviewRow = {
  publisherId: string;
  publisherName: string;
  bookCount: number;
  sampleBooks: Array<{ bookId: string; title: string; author: string; year?: number }>;
  recommendedAction: "add_mapping" | "review_parent_publisher" | "ignore";
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const mappingPath = path.join(root, "sources", "imprint-normalization.json");
const outputPath = path.join(root, "sources", "enrichment", "imprints.normalized.json");
const reviewPath = path.join(root, "data", "public", "imprint-review-queue.json");
const sourceId = "source-imprint-normalization";

async function main() {
  const generatedAt = new Date().toISOString();
  const mappingFile = JSON.parse(await fs.readFile(mappingPath, "utf8")) as MappingFile;
  const mappingsByRawName = new Map(mappingFile.mappings.map((mapping) => [normalizeName(mapping.raw), mapping]));
  const publishersById = new Map(data.publishers.map((publisher) => [publisher.id, publisher]));
  const imprintsById = new Map(data.imprints.map((imprint) => [imprint.id, imprint]));
  const booksByPublisher = new Map<string, Book[]>();

  for (const book of data.books) {
    if (!book.publisherId || book.imprintId) continue;
    const values = booksByPublisher.get(book.publisherId) ?? [];
    values.push(book);
    booksByPublisher.set(book.publisherId, values);
  }

  const patch: NormalizedPatch = {
    generatedAt,
    notes: "Generated by scripts/normalize-imprints.ts from sources/imprint-normalization.json. This promotes curated raw catalog publisher strings into explicit imprints and parent publishers.",
    books: {},
    imprints: {},
    publishers: {},
    sources: {
      [sourceId]: {
        id: sourceId,
        label: "Curated raw-publisher to imprint normalization",
        url: "",
        accessedAt: generatedAt,
        confidence: "manual",
        field: "publisher",
        note: mappingFile.notes,
      },
    },
  };
  const reviewRows: ReviewRow[] = [];

  for (const book of data.books) {
    if (!book.imprintId || !book.sourceIds.includes(sourceId)) continue;
    const imprint = imprintsById.get(book.imprintId);
    const publisher = book.publisherId ? publishersById.get(book.publisherId) : undefined;
    patch.books[book.id] = {
      publisherId: book.publisherId,
      imprintId: book.imprintId,
      sourceIds: [...new Set([...book.sourceIds, sourceId])],
    };
    if (publisher) {
      patch.publishers[publisher.id] = {
        id: publisher.id,
        name: publisher.name,
        sourceIds: [...new Set([...publisher.sourceIds, sourceId])],
      };
    }
    if (imprint) {
      patch.imprints[imprint.id] = {
        id: imprint.id,
        name: imprint.name,
        publisherId: imprint.publisherId ?? book.publisherId,
        sourceIds: [...new Set([...imprint.sourceIds, sourceId])],
      };
    }
  }

  for (const [publisherId, books] of booksByPublisher) {
    const publisher = publishersById.get(publisherId);
    if (!publisher) continue;
    const mapping = mappingsByRawName.get(normalizeName(publisher.name));
    if (!mapping) {
      reviewRows.push(toReviewRow(publisherId, publisher.name, books));
      continue;
    }

    const normalizedPublisherId = `publisher-${slugify(mapping.publisher)}`;
    const normalizedImprintId = `imprint-${slugify(mapping.imprint)}`;
    patch.publishers[normalizedPublisherId] = {
      id: normalizedPublisherId,
      name: mapping.publisher,
      sourceIds: [sourceId],
    };
    patch.imprints[normalizedImprintId] = {
      id: normalizedImprintId,
      name: mapping.imprint,
      publisherId: normalizedPublisherId,
      sourceIds: [sourceId],
    };
    for (const book of books) {
      patch.books[book.id] = {
        publisherId: normalizedPublisherId,
        imprintId: normalizedImprintId,
        sourceIds: [...new Set([...book.sourceIds, sourceId])],
      };
    }
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.mkdir(path.dirname(reviewPath), { recursive: true });
  await fs.writeFile(outputPath, `${JSON.stringify(sortPatch(patch), null, 2)}\n`);
  await fs.writeFile(
    reviewPath,
    `${JSON.stringify({
      generatedAt,
      mappedBooks: Object.keys(patch.books).length,
      mappedImprints: Object.keys(patch.imprints).length,
      unresolvedPublisherStrings: reviewRows.length,
      review: reviewRows.sort((a, b) => b.bookCount - a.bookCount || a.publisherName.localeCompare(b.publisherName)).slice(0, 250),
    }, null, 2)}\n`,
  );

  console.log(`Normalized imprints for ${Object.keys(patch.books).length} books. Review queue has ${reviewRows.length} unresolved publisher strings.`);
}

function toReviewRow(publisherId: string, publisherName: string, books: Book[]): ReviewRow {
  return {
    publisherId,
    publisherName,
    bookCount: books.length,
    sampleBooks: books.slice(0, 5).map((book) => ({
      bookId: book.id,
      title: book.title,
      author: book.authors.map((author) => author.name).join(", "),
      year: book.publicationYear,
    })),
    recommendedAction: books.length >= 2 ? "add_mapping" : "review_parent_publisher",
  };
}

function sortPatch(patch: NormalizedPatch): NormalizedPatch {
  return {
    ...patch,
    books: sortObject(patch.books),
    imprints: sortObject(patch.imprints),
    publishers: sortObject(patch.publishers),
    sources: sortObject(patch.sources),
  };
}

function sortObject<T>(value: Record<string, T>) {
  return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)));
}

function normalizeName(value: string) {
  return value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/&/g, " and ").replace(/\bthe\b/g, "").replace(/[^a-z0-9]+/g, " ").trim();
}

function slugify(input: string) {
  return input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
